Add lookup endpoint for external services to find users by their own id
NodeBB/nodebb-plugin-sso-oauth2-multiple pull request #86
Opened 2024-11-07 01:39 UTC by Brutus5000

2024-12-15 22:11 UTC, Brutus5000 commented
@julianlam Any feedback?

2025-03-05 19:32 UTC, barisusakli commented on lib/controllers.js
> +	}
missing a return here

2025-03-06 14:44 UTC, julianlam commented on lib/controllers.js
> +	}
Alternatively, you can `return next()` in order to invoke the regular api 404 handler. You'll have to add `next` to the method parameters.

2025-03-06 14:45 UTC, julianlam requested changes
LGTM except for the missing return and doc changes.

2025-03-10 15:20 UTC, julianlam approved these changes

2025-03-10 15:20 UTC, merged

2025-03-10 15:21 UTC, julianlam commented
v1.5.0